all:
	pdflatex dux.tex
	bibtex dux.aux
	pdflatex dux.tex
	pdflatex dux.tex

martin:
	pdflatex dux.tex
	bibtex dux.aux
	pdflatex dux.tex
	pdflatex dux.tex
	open dux.pdf

clean:
	rm -rf *.blg *.log *.pdf *.bbl *.aux *~
