dist: trusty
sudo: required
language: java
os:
- linux
env:
- V=0.8.0
before_install:
- openssl aes-256-cbc -K $encrypted_dabcf2a73fc5_key -iv $encrypted_dabcf2a73fc5_iv
  -in credentials/GOOGLE_APPLICATION_CREDENTIALS.enc -out credentials/GOOGLE_APPLICATION_CREDENTIALS
  -d
- export GOOGLE_APPLICATION_CREDENTIALS=credentials/GOOGLE_APPLICATION_CREDENTIALS
- export URL="https://github.com/bazelbuild/bazel/releases/download/${V}/bazel-${V}-installer-linux-x86_64.sh"
- wget -O install.sh "${URL}"
- chmod +x install.sh
- ./install.sh --user
- rm -f install.sh
script:
- bazel build //:dux
- cd tst
- sh ignoreproj.sh
- sh smoke.sh
- sh blacklist.sh
- sh configcheck.sh
notifications:
  email: false